### ISSUE TITLE
Using v-frag directive then changing routes multiple times

### ISSUE THREAD

**Issue by stephenjason89** [privatenumber/vue-frag#26] opened 2021-03-30 15:57 UTC
I am using nuxt and in my pages directory,

I have a page named abc.vue
it is wrapped with a <div v-frag>

now, i have another page named def.vue
also wrapped in <div v-frag>

switching between those pages back and fort with vue router causes

frag.esm.js?76e6:1 Uncaught TypeError: Cannot read property 'before' of undefined

**Comment by privatenumber** [comment] 2021-04-19 08:09
Sorry I don't really understand this report, but I'm going to guess it's a duplicate of https://github.com/privatenumber/vue-frag/issues/27 considering the Nuxt router usage.

**Closed by privatenumber** 2021-04-19 08:09 UTC
