### ISSUE TITLE
Eslint error: Fragment not found in 'vue-frag'

### ISSUE THREAD

**Issue by aslak01** [privatenumber/vue-frag#68] opened 2022-11-04 09:42 UTC
Hey,

I get this error when importing fragment in a component:

<img width="754" alt="Screenshot 2022-11-04 at 10 35 08" src="https://user-images.githubusercontent.com/25505610/199940650-fcd87b4a-95ee-42f3-8414-bb9bc0bec94b.png">

Workaround is to import like this:

```ts
import Frag from 'vue-frag'
(...)
  components: {
    Fragment: Frag.Fragment,
  }
```

Edit: strike the workaround, it got rid of the error, but the plugin stopped working. Just disabling eslint instead for now.

**Comment by privatenumber** [comment] 2022-11-17 15:52
Maybe [`esModuleInterop`](https://www.typescriptlang.org/tsconfig#esModuleInterop) is not enabled?

If not, can you provide a minimal reproduction?
I can't help you with the information you provided so far.

**Comment by aslak01** [comment] 2022-11-24 00:18
I'm not working on that project anymore, so I'm sorry, but I can't really answer your suggestion or provide a minimal repro. It is a Vue 2 TS project, so it's quite possible that the problem is esModuleInterop not being enabled. I just reported it here because I didn't see anything similar from other packages, so if it is some TS setting causing it, it might warrant a comment in the readme or something.

**Comment by privatenumber** [comment] 2022-11-24 02:12
It's standard TypeScript practice to enable `esModuleInterop` when using `import` statements that compile to CommonJS.

Closing this out as un-actionable since you can't provide more information.

**Closed by privatenumber** 2022-11-24 02:12 UTC
